#定数情報

#JRA kjdbテーブル
TBL_KJDB_PROGRAM_HEADER = "ProgramHeader" 
TBL_KJDB_RACE_HEADER = "RaceHeader" 
TBL_KJDB_RACE_RESULT_AT = "HorseResult_{}"
TBL_KJDB_RACE_RESULT = "HorseResult"
VIEW_KJDB_RACE_RESULT = "HorseResult"
TBL_KJDB_FAMILY_TREE = "FamilyTree"
TBL_KJDB_BLOOD_SCORE = "BloodScore"
TBL_KJDB_STUD_SCORE = "StudScore"
TBL_KJDB_TRAINER_SCORE = "TrainerScore"
TBL_KJDB_JOCKEY_SCORE = "JockeyScore"
TBL_KJDB_BASE_TIME = "BaseTime"
TBL_KJDB_HV_CACHE_VALIABLE_AT = "HistoryVariables_{}"
TBL_KJDB_AVERAGE_TIME_MAIDEN_RACE = "AverageTimeMaidenRace" 
TBL_KJDB_TIME_DESCRIBES = "TimeDescribes"
TBL_KJDB_MASTER_JOCKEY = "MasterJockey"
TBL_KJDB_MASTER_SIRE = "MasterSire"
TBL_KJDB_MASTER_TRAINER = "MasterTrainer"
TBL_KJDB_MASTER_DEPARTMENT = "MasterDepartment"
#kjdb教師データテーブル
TBL_KJDB_PREDICT_VALIABLE = "PredictorVariablesData"

TBL_KJDB_PREDICT_CACHE_VALIABLE = "PredictorVariables"
TBL_KJDB_PREDICT_CACHE_VALIABLE_AT = "PredictorVariables_{}"
TBL_KJDB_STATISTICS_CACHE_VALIABLE = 'StatisticsVariables'
TBL_KJDB_STATISTICS_CACHE_VALIABLE_AT = 'StatisticsVariables_{}'
TBL_KJDB_TE_CACHE_VALIABLE = "TargetEncodingVariables"
TBL_KJDB_TE_CACHE_VALIABLE_AT= "TargetEncodingVariables_{}"
TBL_KJDB_HV_CACHE_VALIABLE = "HistoryVariables"
TBL_KJDB_TE_BPD = "TeBPD"
TBL_KJDB_TE_BD = "TeBD"
TBL_KJDB_TE_C = "TeC"
TBL_KJDB_TE_BPDSY = "TeBPDSY"
TBL_KJDB_TE_BPDJY = "TeBPDJY"
TBL_KJDB_TE_BPDTY = "TeBPDTY"
TBL_KJDB_TE_BPDS = "TeBPDS"
TBL_KJDB_TE_TEMP = 'TeTemp'
TBL_KJDB_PREDICT_VALUE = "Predict_{0}"

TBL_KJDB_LA_MUL_COUNT = "LineageMulCount"
TBL_KJDB_LA_WIN_COUNT = "LineageWinCount"
TBL_KJDB_LA_COUNT = "LineageCount"

TBL_KJDB_PREDICT_HISTORY = "PredictHistory"
TBL_KJDB_COMMENT = "Comment"
#SQL Server 用テーブル
TBL_KJVAN_N_RACE = "N_RACE"
TBL_KJVAN_S_RACE = "S_RACE"
TBL_KJVAN_N_UMA = "N_UMA"
TBL_KJVAN_S_UMA = TBL_KJVAN_N_UMA
TBL_KJVAN_N_UMA_RACE = "N_UMA_RACE"
TBL_KJVAN_S_UMA_RACE = "S_UMA_RACE"
TBL_KJVAN_N_SANKU = "N_SANKU"
TBL_KJVAN_N_BANUSI = "N_BANUSI"
TBL_KJVAN_N_HANSYOKU = "N_HANSYOKU"
TBL_KJVAN_N_CHOKYO = "N_CHOKYO"
TBL_KJVAN_N_KISYU = "N_KISYU"
TBL_KJVAN_N_HANRO = "N_HANRO"
TBL_KJVAN_S_ODDS_TANPUKU = "S_ODDS_TANPUKU"
TBL_KJVAN_S_JODDS_TANPUKU = "S_JODDS_TANPUKU"
TBL_KJVAN_S_HARAI = "S_HARAI"
TBL_KJVAN_N_JODDS_TANPUKU= "N_JODDS_TANPUKU"
TBL_KJVAN_N_JODDS_TANPUKUWAKU_HEAD= "N_JODDS_TANPUKUWAKU_HEAD"
TBL_KJVAN_N_SCHEDULE = "N_SCHEDULE"
TBL_KJVAN_N_MINING = "N_MINING"
TBL_KJVAN_S_MINING = "S_MINING"
TBL_KJVAN_N_TAISENGATA_MINING = "N_TAISENGATA_MINING"
TBL_KJVAN_S_TAISENGATA_MINING = "S_TAISENGATA_MINING"


# クラスタサイズ
CLUSTER_SIZE_OF_JOCKEY=30
CLUSTER_SIZE_OF_SIRE=30
CLUSTER_SIZE_OF_TRAINER=30

#負担重量
MIN_BURDEN=47.0
MAX_BURDEN=80.0
#最大出走数
MAX_HORSE_COUNT=18


#VOID program_id
VOID_PID = '0000000000'
#加重平均最大数
WA_MAX_COUNT = 5